/* Generated By:JavaCC: Do not edit this line. minilengcompilerConstants.java */
package JavaCC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface minilengcompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tPROGRAMA = 11;
  /** RegularExpression Id. */
  int tVAR = 12;
  /** RegularExpression Id. */
  int tAND = 13;
  /** RegularExpression Id. */
  int tOR = 14;
  /** RegularExpression Id. */
  int tNOT = 15;
  /** RegularExpression Id. */
  int tPRINCIPIO = 16;
  /** RegularExpression Id. */
  int tFIN = 17;
  /** RegularExpression Id. */
  int tSI = 18;
  /** RegularExpression Id. */
  int tENT = 19;
  /** RegularExpression Id. */
  int tSI_NO = 20;
  /** RegularExpression Id. */
  int tFSI = 21;
  /** RegularExpression Id. */
  int tMQ = 22;
  /** RegularExpression Id. */
  int tFMQ = 23;
  /** RegularExpression Id. */
  int tMAS = 24;
  /** RegularExpression Id. */
  int tMENOS = 25;
  /** RegularExpression Id. */
  int tMUL = 26;
  /** RegularExpression Id. */
  int tDIVENT = 27;
  /** RegularExpression Id. */
  int tDIVDECIMAL = 28;
  /** RegularExpression Id. */
  int tMOD = 29;
  /** RegularExpression Id. */
  int tESCRIBIR = 30;
  /** RegularExpression Id. */
  int tLEER = 31;
  /** RegularExpression Id. */
  int tVAL = 32;
  /** RegularExpression Id. */
  int tREF = 33;
  /** RegularExpression Id. */
  int tENTERO = 34;
  /** RegularExpression Id. */
  int tBOOLEANO = 35;
  /** RegularExpression Id. */
  int tCARACTER = 36;
  /** RegularExpression Id. */
  int tTRUE = 37;
  /** RegularExpression Id. */
  int tFALSE = 38;
  /** RegularExpression Id. */
  int tENTACAR = 39;
  /** RegularExpression Id. */
  int tCARAENT = 40;
  /** RegularExpression Id. */
  int tACCION = 41;
  /** RegularExpression Id. */
  int tMAYOR = 42;
  /** RegularExpression Id. */
  int tMENOR = 43;
  /** RegularExpression Id. */
  int tIGUAL = 44;
  /** RegularExpression Id. */
  int tMAI = 45;
  /** RegularExpression Id. */
  int tMEI = 46;
  /** RegularExpression Id. */
  int tNI = 47;
  /** RegularExpression Id. */
  int tOPAS = 48;
  /** RegularExpression Id. */
  int tPTOCOMA = 49;
  /** RegularExpression Id. */
  int tCOMA = 50;
  /** RegularExpression Id. */
  int tABREPARENTESIS = 51;
  /** RegularExpression Id. */
  int tCIERREPARENTESIS = 52;
  /** RegularExpression Id. */
  int tIDENTIFICADOR = 53;
  /** RegularExpression Id. */
  int tCONSTENTERA = 54;
  /** RegularExpression Id. */
  int tCONSTCHAR = 55;
  /** RegularExpression Id. */
  int tCONSTCAD = 56;
  /** RegularExpression Id. */
  int CONSTANT = 57;
  /** RegularExpression Id. */
  int DIGIT = 58;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENTONELINE = 1;
  /** Lexical state. */
  int COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"%%\"",
    "\"%\"",
    "\"\\n\"",
    "\"%%\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "\"programa\"",
    "\"var\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"principio\"",
    "\"fin\"",
    "\"si\"",
    "\"ent\"",
    "\"si_no\"",
    "\"fsi\"",
    "\"mq\"",
    "\"fmq\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"div\"",
    "\"mod\"",
    "\"escribir\"",
    "\"leer\"",
    "\"val\"",
    "\"ref\"",
    "\"entero\"",
    "\"booleano\"",
    "\"caracter\"",
    "\"true\"",
    "\"false\"",
    "\"entacar\"",
    "\"caraent\"",
    "\"accion\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\":=\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<tIDENTIFICADOR>",
    "<tCONSTENTERA>",
    "<tCONSTCHAR>",
    "<tCONSTCAD>",
    "<CONSTANT>",
    "<DIGIT>",
  };

}
